### ISSUE TITLE
#3.3 man -> mandb

### ISSUE THREAD

**Issue by keithy** [NixOS/nix-pills#123]
K

**Comment by JohnAZoidberg** [comment]
@keithy Does this mean anything?

**Comment by keithy** [comment]
https://nixos.org/nixos/nix-pills/enter-environment.html#idm140737316579392

**Comment by DrPyser** [comment]
Actually, I think it should be [`man-db`](https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=man-db). `mandocs` is described as a suite of build tools for man and doc pages.

**Comment by ThoenigAdrian** [comment]
Thx for opening this issue i just came accross this(following the tutorial) and now i know with what i should replace it

**Comment by jonringer** [comment]
addressed by #157
