### ISSUE TITLE
Page Not Found https://nixos.org/nixos/nix-pills/

### ISSUE THREAD

**Issue by grantzvolsky** [NixOS/nix-pills#130]
The official site\[0\] is down or was moved without a redirect.

\[0\]: [https://nixos.org/nixos/nix-pills/](https://nixos.org/nixos/nix-pills/)

**Comment by rnhmjoj** [comment]
It works for me, now. What happened?

**Comment by grantzvolsky** [comment]
It is back up now. I'm sure I had the right url because I'm accessing it through bookmarks & search engine results were broken too.

If anyone encounters this in the future, you can clone this repo & build the manual yourself using this oneliner from the README:
```
nix-build release.nix && firefox result/share/doc/nix-pills/index.html
```

**Comment by grantzvolsky** [comment]
p.s. I got the default 404 error of the website: https://nixos.org/404-hello-world

**Comment by jonringer** [comment]
most likely related to https://discourse.nixos.org/t/announcement-moving-nixos-org-to-netlify/6212/9

I'm going to consider this closed.

thank you @grantzvolsky for opening a ticket :)
