### ISSUE TITLE
Pill 9 Link to Dolstra's PhD Thesis returns Not Found

### ISSUE THREAD

**Issue by aaronchall** [NixOS/nix-pills#131]
I don't know if this file should be there and it is missing, if we should point to another location, or remove the reference.

**Comment by JohnAZoidberg** [comment]
cc @edolstra

**Comment by ccressent** [comment]
As of September 30th 2020, it links to http://nixos.org/~eelco/pubs/phd-thesis.pdf and it's working fine!
Should this issue be closed?

**Comment by rnhmjoj** [comment]
I think so, the links appears to be working.
