### ISSUE TITLE
Pill 8.3 slight grammatical issue

### ISSUE THREAD

**Issue by tzx** [NixOS/nix-pills#133]
I'm not sure if this is correct but the the line:
> 1. First drop in the scope the **magic** pkgs attribute set.

is confusing to me. Is it supposed to be adjective magical? Also what does magic even mean in this case?

**Comment by gengshuhui** [comment]
> I'm not sure if this is correct but the the line:
> 
> > 1. First drop in the scope the **magic** pkgs attribute set.
> 
> is confusing to me. Is it supposed to be adjective magical? Also what does magic even mean in this case?

"magic" is also an adjective.

**Comment by tzx** [comment]
I will close this. It is "magic" after using nix more.
