### ISSUE TITLE
Broken papers link in section 1.2

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#19]
The first sentence in section 1.2 (below) has a "related papers" link, which returns a 404.

https://nixos.org/nixos/nix-pills/why-you-should-give-it-a-try.html

**Comment by grahamc** [comment]
We could delete it or link to https://nixos.org/~eelco/pubs/, what do you think?

**Comment by gfixler** [comment]
Between those choices, I think I'd prefer your link to the list of publications. I'd slightly more prefer duplicating that page to `http://nixos.org/docs/papers.html`, and filtering out the nix-irrelevant links, perhaps with a link to the rest of Eelco's publications at the bottom.

**Comment by grahamc** [comment]
Evidently this page as deleted on purpose in 2014. We’ll have to ask eelco
why :)

**Comment by grahamc** [comment]
I just removed the link for now :)
