### ISSUE TITLE
no bin in sqlite directory

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#20]
In pill #2, section 2.3, I find the following line:

Inspect it running /nix/store/*sqlite*/bin/sqlite3 /nix/var/nix/db/db.sqlite

My sqlite folder on a clean install via the install script (first timer!) has no bin folder, only a lib folder.

I received instruction from #nixos to try the following:

`nix-env -iA nixpkgs.sqlite`

This worked. I ended up in an sqlite3 REPL. I know nothing about sqlite3, though :)

Note: I did not have nix-env on my path, and was told to run the line at the end of the install script output, which I completely missed in the noise of the install output. I think it should also be mentioned clearly in the pill so it's not overlooked.

**Comment by grahamc** [comment]
Thanks! I added a note about installing sqlite first. In 61771a7 I added a note about reopening windows.
