### ISSUE TITLE
Section 3.3 line needs clarification

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#22]
Just under the first code block in Pill 3, section 3.3:

> Now that's interesting. When only nix-1.7 was installed, bin/ was a symlink to nix-1.7. Now it's a real directory, no symlink.

What did I do to make it not a symlink? Hasn't 'only nix-1.7' been installed the whole time?

**Comment by gfixler** [comment]
Update: I was told on #nixos that installing `man` and `nix-repl` is what caused the bin directory to switch from symlink to real folder. This disambiguated that line a bit for me. I was thinking "only 1.7" meant an earlier version, or maybe something else entirely. I didn't see it as "only nix-1.7" and not any other packages, like `man`, because I didn't see nix-1.7 as existing at the same level; I though nix was higher up, and utilities were being installed into it.

**Comment by Profpatsch** [comment]
Would you like to open a PR?

**Comment by grahamc** [comment]
Thank you!
