### ISSUE TITLE
Small discrepancy in pill 7.7

### ISSUE THREAD

**Issue by MathiasMalandain** [NixOS/nix-pills#221]
## Issue

Pill 7.7 explains how line 1 of `simple.nix` uses a `with` statement for getting the derivations imported from `nixpkgs` into scope. However, the actual code of `simple.nix` relies on a `let`-expression instead.

## Possible fixes

* Just rewrite, either the text itself, or the `simple.nix` code.
* Bonus points if you do both and explain the differences (if any? still learning my Nix...), but this would maybe bloat this pill a little.

I, for one, think the `let`-expression is pretty clear and readable, but, full disclaimer: I am an OCaml programmer.

## Footnote

I really enjoy the pills so far, thanks a lot!

**Comment by drupol** [comment]
I think it should be rephrased, indeed, as such:

> In the first line of `simple.nix`, we have an import function. Recall that import accepts one argument, a nix file to load. In this case, the contents of the file evaluated to a function.

Now, the difference between the two... 

1. With `let...in`
  This is creating a local variable `pkgs = import <nixpkgs> {};` and then, that variable `pkgs` is used throughout the rest of the expression.
2. With `with`:
  I haven't seen the expression with `with`, but I guess it should be something like: 
  ```with import <nixpkgs> {}; pkgs.stdenv.mkDerivation { ...```
  Using `with` here is syntactically valid. However, it introduces confusion. It will basically
  try to bind all the unknown variables to the result of `import <nixpkgs> {};`. That's the
  reason why it introduces confusion. It's also very difficult for the future potential static
  analysis tools to know to which variable another variable is bound to. That's for all these 
  reasons I'm trying to avoid the use of `with`. I do use it only when it is a trivial case and 
  usually with a list, such as: `meta.maintainers = with lib.maintainers; [ drupol ];`

**Comment by fricklerhandwerk** [comment]
@MathiasMalandain would be great if you could open a PR to fix the description text. Using the `let` expression is definitely the preferred way these days: https://nix.dev/recipes/best-practices#with-scopes

**Comment by MathiasMalandain** [comment]
Thanks a lot for the clear, detailed explanations and the link to the "best practices" page.
