### ISSUE TITLE
'' within ''?

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#23]
In Nix Pill 4, section [4.3. Strings](https://nixos.org/nixos/nix-pills/basics-of-language.html#idm140737316618912), last code block:

> Escaping ${...} within double quoted strings is done with the backslash. Within two single quotes, it's done with '':

`nix-repl> ''test ''${foo} test''`

Is that meant to be two single quotes before `${foo}`? I thought it was supposed to be a double quote.

**Comment by Profpatsch** [comment]
No, two single quotes escape `${}` inside `''` blocks.

```
nix-repl> ''foo${toString 1}''
"foo1"

nix-repl> ''foo''${toString 1}''
"foo${toString 1}"
```

(`nix-shell -p nix-repl` to install nix-repl)

**Comment by gfixler** [comment]
Ah, in the text above the code the two single quotes looked just like a double quote. I should have selected them to see. I also now find "within double quoted strings" to be a bit ambiguous (sounds like strings delimited by double-qutotes, i.e. "foo," but I suppose it's cleared up by the example. Closing, and thanks.

**Comment by grahamc** [comment]
I wonder if we can make this more clear.
