### ISSUE TITLE
error: selector 'strategoxt' matches no derivations

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#24]
In Pill 6, [6.2. Digression about .drv files](https://nixos.org/nixos/nix-pills/our-first-derivation.html#idm140737316480128), I'm instructed to install strategoxt thus:

`$ nix-env -i strategoxt`

This results in the following:

`error: selector 'strategoxt' matches no derivations`

I am a new user/nix learner on a clean Ubuntu install, following the nix pills guides in order.

**Comment by Profpatsch** [comment]
Is this specific program needed anywhere else?
If not it would be sensible to replace it with GNU/hello (`hello`). Could you open a PR?

**Comment by gfixler** [comment]
I'm not sure how `hello` fits in. `strategoxt` is installed at this point for the purposes of pretty-printing .drv files, not just to try out installation. We tried out installation earlier with `nix-repl`.

**Comment by gfixler** [comment]
Related issue from NixOS / nixpkgs: https://github.com/NixOS/nixpkgs/issues/25371

**Comment by grahamc** [comment]
In c338957a7c7dc9d2aa09a670ee6b9823ae5290cf I sort of address this, even though `indent` isn't a wonderful substitution.

**Comment by grahamc** [comment]
(If you have improvements, please suggest them! Thank you for the issue!)

**Comment by Ericson2314** [comment]
`nix show-derivation` with 1.12 will be the proper solution.
