### ISSUE TITLE
Pill 3 - Dead links to Nix reference manual

### ISSUE THREAD

**Issue by Cully-Curwen** [NixOS/nix-pills#250]
In Pill 3, Enter the Environment, all the links to the nix reference manual are dead links

https://github.com/NixOS/nix-pills/blob/42532b09a3ad71a4ef7044a5f3cc0644ec11305d/pills/03-enter-environment.md?plain=1#L39

https://github.com/NixOS/nix-pills/blob/42532b09a3ad71a4ef7044a5f3cc0644ec11305d/pills/03-enter-environment.md?plain=1#L65

https://github.com/NixOS/nix-pills/blob/42532b09a3ad71a4ef7044a5f3cc0644ec11305d/pills/03-enter-environment.md?plain=1#L109

https://github.com/NixOS/nix-pills/blob/42532b09a3ad71a4ef7044a5f3cc0644ec11305d/pills/03-enter-environment.md?plain=1#L199

https://github.com/NixOS/nix-pills/blob/42532b09a3ad71a4ef7044a5f3cc0644ec11305d/pills/03-enter-environment.md?plain=1#L222

The issue seem to be the use of "/stable" in the path. When removed the links work

**Comment by zaiquiriw** [comment]
There is also a dead link in pill 4 (I haven't searched for more).

**Comment by zaiquiriw** [comment]
Found related change on nix.dev https://github.com/NixOS/nix.dev/pull/999
