### ISSUE TITLE
What is `~/.profile`?

### ISSUE THREAD

**Issue by kuraga** [NixOS/nix-pills#256]
There are:

https://github.com/NixOS/nix-pills/blob/3de6eec231cae251366b79d641e2f9110470c6ff/pills/02-install-on-your-running-system.md#L105

https://github.com/NixOS/nix-pills/blob/3de6eec231cae251366b79d641e2f9110470c6ff/pills/02-install-on-your-running-system.md#L118

https://github.com/NixOS/nix-pills/blob/3de6eec231cae251366b79d641e2f9110470c6ff/pills/03-enter-environment.md#L9

Are they `~/.nix-profile` instead?

**Comment by SuperSandro2000** [comment]
It is similar to ~/.bashrc but for all shells and should contain code that works in bash, zsh, etc, so mostly posix.

see https://man.cx/bash#:~:text=When%20bash%20is%20invoked,to%20inhibit%20this%20behavior.

**Comment by kuraga** [comment]
Aha, phew, it's just the regular `~/.profile`...
