### ISSUE TITLE
broken `strip` link in Pill 9

### ISSUE THREAD

**Issue by gfixler** [NixOS/nix-pills#28]
In Pill 9, final sentence of section [9.3. Runtime dependencies](https://nixos.org/nixos/nix-pills/automatic-runtime-dependencies.html#idm140737316221856):

> For that, the well known [strip](http://unixhelp.ed.ac.uk/CGI/man-cgi?strip) can be used.

The `strip` link seems dead, as does the entire `http://unixhelp.ed.ac.uk` subdomain.

**Comment by grahamc** [comment]
Would you mind sending a PR removing the link and replacing the link with `<command>strip</command>`?

**Comment by grahamc** [comment]
I went ahead and did it while closing other issues :) Thank you!
