### ISSUE TITLE
License the Nix Pills

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix-pills#36]
Hello nix-pill contributors, bad news! The pills are currently unlicensed! I am planning on licensing the current work as CC-BY-SA-4.0: https://creativecommons.org/licenses/by-sa/4.0/

This is everyone who has contributed changes. ***Please*** get back to this issue ASAP confirming CC-BY-SA-4.0 is OK with you. I would really like for this to be done by Wednesday, but the sooner the better.

 - [x] @ankhers 
 - [x] @Anton-Latukha 
 - [x] @disassembler 
 - [x] @ecnerwala 
 - [x] @efx 
 - [x] @frontsideair 
 - [x] @gfixler
 - [x] @grahamc
 - [x] @ixxie 
 - [x] @lheckemann 
 - [x] @lethalman
 - [x] @michaelpj 
 - [x] @Munksgaard 
 - [x] @qrilka 
 - [x] @richardipsum 
 - [x] @vaibhavsagar 

Thanks!

**Comment by ankhers** [comment]
I'm okay with that.

**Comment by lheckemann** [comment]
I'm fine with it. Are we now going to get github notifications for each person agreeing? >_>

**Comment by frontsideair** [comment]
I'm also okay.

**Comment by grahamc** [comment]
@lheckemann you can "unsubscribe" on the right? :)

**Comment by ankhers** [comment]
Yes. But I think you could unsubscribe from the issue and stop getting
notifications.

**Comment by Profpatsch** [comment]
A shame that I’m no contributor, I’d have answered with https://www.youtube.com/watch?v=XftdS9_KKGc

**Comment by ecnerwala** [comment]
I'm fine with it.

**Comment by disassembler** [comment]
I can't check the box, but I'm cool with it, also responded in IRC earlier.

**Comment by richardipsum** [comment]
I'm fine with it

**Comment by ixxie** [comment]
Im fine with it!

**Comment by Munksgaard** [comment]
Sounds great, go ahead :-)

**Comment by qrilka** [comment]
I'm fine with it

**Comment by vaibhavsagar** [comment]
Fine by me :smiley:!

**Comment by gfixler** [comment]
Sounds good to me.

**Comment by efx** [comment]
I approve. Good call on licensing before any patent battles.

**Comment by Anton-Latukha** [comment]
Sure. I agree.

**Comment by grahamc** [comment]
```
From: Luca Bruno
Date: Sat, 16 Dec 2017 10:30:02 +0000
Subject: Re: License for Nix Pills?
To: Daniel Peebles
Cc: Graham Christensen

I see, that sounds great. I don't have any opinion on the license, just
pick whatever you think is best :)

2017-12-14 17:49 GMT+00:00 Daniel Peebles:

> We're looking at solidifying the NixOS foundation's legal standing [...]
> and as part of that are digging up licenses for various components that we
> host, including code, documentation and the pills.
>
>
> On Thu, Dec 14, 2017 at 12:48 PM, Luca Bruno
> wrote:
>
>> What's the need for a license at all?
>>
>> 2017-12-14 17:43 GMT+00:00 Daniel Peebles:
>>
>>> Thanks, that's very generous!
>>>
>>> May I suggest Creative Commons BY? See https://creativecommons.or
>>> g/licenses/
>>>
>>>>
>>>> CC BY
>>>> This license lets others distribute, remix, tweak, and build upon your
>>>> work, even commercially, as long as they credit you for the original
>>>> creation. This is the most accommodating of licenses offered. Recommended
>>>> for maximum dissemination and use of licensed materials.
>>>
>>>
>>> Otherwise, CC BY-SA would force downstream users to continue to license
>>> it under similar terms, if you'd prefer.
>>>
>>>
>>> On Thu, Dec 14, 2017 at 12:39 PM, Luca Bruno
>>> wrote:
>>>
>>>> Uhm don't know :) They are there open for everyone to use and modify I
>>>> guess :)
>>>>
>>>> 2017-12-14 16:30 GMT+00:00 Daniel Peebles:
>>>>
>>>>> Hi Luca,
>>>>>
>>>>> Since your wonderful Nix pills have been migrated to the Nix docs
>>>>> site, I was wondering what license you wrote the originals under. Do you
>>>>> have any opinions on that?
>>>>>
>>>>> Thank you,
>>>>> Dan
>>>>>```

**Comment by grahamc** [comment]
Licensed in 89e5624b55e3501104af8aa3079e583e3baaa28e! Thank you everyone for  being so prompt!
