### ISSUE TITLE
Pill 20 which is not in the PATH

### ISSUE THREAD

**Issue by dudebout** [NixOS/nix-pills#62]
To go around https://github.com/NixOS/nix-pills/issues/61, I built the first derivation against the current version of nixpkgs. This fails because `which` is not in the `PATH`. Adding `nixpkgs.which` to the `buildInputs` array fixes the issue. Not sure if `which` used to be in the bootstrap executables.

I also had to add `unpackPhase = "true";` since [newer `stdenv` default unpackPhase requires that either `$src` or `$srcs` be set](https://github.com/NixOS/nixpkgs/issues/23099)

**Comment by Ericson2314** [comment]
Nah it never was. My bad forgetting about that. `which` -> `command -v` will do the trick.
