### ISSUE TITLE
Upgrade docs to Nix 2.0

### ISSUE THREAD

**Issue by sseefried** [NixOS/nix-pills#68]
This is more of a question than an issue. (Please feel free to close this issue once it is answered).

Would it be worthwhile if we upgraded the pills to Nix 2.0? There are many commands in the pills
that just won't work with Nix 2.0 e.g. `nix-build` is now `nix build`.

Also, there are quite a few differences between Nix installation, directory structure, etc on Mac OS X and Linux. Would it be worth having a Mac OS X section in each pill when things are different?

**Comment by Mic92** [comment]
They still work, `nix-build` still exists, but it might be worth upgrading.
I would add remarks for directory structure and running commands, if it is significant for understanding, i.e not duplicating command output just because the store path prefixes are different.

**Comment by grahamc** [comment]
The "nix" command is still beta. Better keep the stable commands until the
nix command stabilizes.

**Comment by sseefried** [comment]
Thanks @grahamc. I'm going to close this for now. Thank you everyone for feedback.
