### ISSUE TITLE
Chapter 8. Generic Builders. Builder script can't unpack tarball

### ISSUE THREAD

**Issue by khssnv** [NixOS/nix-pills#87]
## Issue description

Copy-pasted files from [Chapter 8. Generic Builders](https://nixos.org/nixos/nix-pills/generic-builders.html) invokes `nix-build` with an error.

<details>
  <summary> $ nix-build hello.nix  </summary>

```bash                                                                                                                                                                    
these derivations will be built:                                                                                                                                                                            
  /nix/store/2wnddhppc3475n2wmixkinfi5qri3dyl-hello.drv                                                                                                                                                     
building '/nix/store/2wnddhppc3475n2wmixkinfi5qri3dyl-hello.drv'...                                                                                                                                         
/nix/store/86k2z0mc023y9qxn8gln4a6kj2a759gx-builder.sh: line 7: tar: No such file or directory                                                                                                              
builder for '/nix/store/2wnddhppc3475n2wmixkinfi5qri3dyl-hello.drv' failed with exit code 127                                                                                                               
error: build of '/nix/store/2wnddhppc3475n2wmixkinfi5qri3dyl-hello.drv' failed
```
</details>

### Steps to reproduce

[![asciicast](https://asciinema.org/a/3qmbnoSSeLmQGVXHZP2agNtx8.svg)](https://asciinema.org/a/3qmbnoSSeLmQGVXHZP2agNtx8)

Please consider there is a file by builder's `src` path available to unpack from user shell.

## Technical details

```bash
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.1023.06fb0253afa (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.1023.06fb0253afa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

P. S. Thanks to authors for the "pills"! They are very helpful in addition to manuals.

**Comment by mhwombat** [comment]
This also works, and is a bit shorter:

```
set -e
unset PATH
for p in $buildInputs $baseInputs; do
  export PATH=$p/bin${PATH:+:}$PATH
done

tar -xf $src

for d in *; do
  if [ -d "$d" ]; then
    cd "$d"
    break
  fi
done

./configure --prefix=$out
make
make install
```

I will generate a pull request for this.

**Comment by mhwombat** [comment]
builder.sh needs $baseInputs on the path as well as $buildInputs.

**Comment by grahamc** [comment]
I'm not sure this is supposed to be fixed, as the document is leaving it up as an exercise to the reader:

```
Complete the new builder.sh by adding $baseInputs in the for loop together with $buildInputs.
```

What do you think? am I misunderstanding the bug report?

**Comment by mhwombat** [comment]
You're right, I didn't see that.

**Comment by kalbasit** [comment]
closed in eff2de0.

**Comment by ddellacosta** [comment]
> You're right, I didn't see that.

@mhwombat FWIW I went through the exact same thing, and only realized my mistake after I found this issue and read grahamc's comment. D'oh.

**Comment by srl295** [comment]
I had only searched open issues apparently, so missed this and #94 while filing #137, sorry.

The wording "Complete the new builder.sh" perhaps could say, "this won't actually work until you…".

**Comment by wolfi089** [comment]
Could you please re-think about this exercise? I'm running through the examples cut&paste and are very happy to see them working out-of-the-box on my machine. This one I feel disturbing (beside this very well written pills).
