### ISSUE TITLE
Pill 3.2 on NixOS selector 'nix-repl' matches no derivations

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nix-pills#89]
I'm on NixOS, so I skipped pill 2. At the beginning of pill 3:
$ nix-env -i nix-repl
error: selector 'nix-repl' matches no derivations

**Comment by Ma27** [comment]
`nix-repl` is deprecated as it's now part of Nix. This needs definitely to be changed, until then simply running `nix repl` should be sufficient :)

**Comment by Ma27** [comment]
Just FYI for the rest, I'm working now on improve chapter three (absolutely not to procrastinate other chores)
